name: progress_alliance
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.0.0
  intl: ^0.19.0
  table_calendar: ^3.1.2
  image_picker: ^1.1.2
  intl_phone_field: ^3.2.0
  otp_text_field: ^1.1.3
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.7.0
  geocoding: ^3.0.0
  custom_info_window: ^1.0.1
  http: ^1.2.1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  pdfx: ^2.6.0
  flutter_rating_bar: ^4.0.1
  pdf: ^3.11.0
  share_plus: ^9.0.0
  pin_code_fields: ^8.0.1
  flutter_screenutil: ^5.9.3
  material_design_icons_flutter: ^7.0.7296
  shimmer: ^3.0.0
  shared_preferences: ^2.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Icons/
    - assets/Images/
    - assets/Logo/
    - assets/pdf/


  fonts:
    - family: Lexend
      fonts:
        - asset: assets/Fonts/Lexend-Regular.ttf
          weight: 200
    - family: Inter
      fonts:
        - asset: assets/Fonts/Inter-VariableFont_slnt,wght.ttf
          weight: 200      